-- CreateEnum
CREATE TYPE "RoomType" AS ENUM ('DELUXE', 'SUITE', 'STANDARD');

-- CreateEnum
CREATE TYPE "BedType" AS ENUM ('KING', 'QUEEN', 'TWIN', 'SINGLE');

-- AlterTable
ALTER TABLE "rooms" ADD COLUMN "room_type" "RoomType" NOT NULL DEFAULT 'STANDARD';
ALTER TABLE "rooms" ADD COLUMN "description" TEXT;
ALTER TABLE "rooms" ADD COLUMN "max_occupancy" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "rooms" ADD COLUMN "bed_type" "BedType" NOT NULL DEFAULT 'QUEEN';
ALTER TABLE "rooms" ADD COLUMN "price_per_night" DECIMAL(10, 2) NOT NULL DEFAULT 0;
ALTER TABLE "rooms" ADD COLUMN "amenities" JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "rooms" ADD COLUMN "images" JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE "rooms" ADD COLUMN "is_active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "rooms" ADD COLUMN "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
